name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run lint:ci

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16, 17 ]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run test:ci

  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build:ci -- --output-path=./dist

      - uses: actions/upload-artifact@v2
        with:
          name: luna-web
          path: dist
